### ISSUE TITLE
Use light theme instead of dark theme

### ISSUE THREAD

**Issue by bnsddk** [Aratramba/sanity-plugin-media-library#33]
Hello,

Thanks a lot for creating this tool, it's great.

If possible, I'd like to theme to be light (same way as your screenshots). Would that be possible?

**Comment by Aratramba** [comment]
I've released a 2.0.0 version using Sanity UI instead of custom theming. The interface is now white and theming is no longer an option. Let me know if that works for you :)

https://www.npmjs.com/package/sanity-plugin-media-library

**Comment by bnsddk** [comment]
> I've released a 2.0.0 version using Sanity UI instead of custom theming. The interface is now white and theming is no longer an option. Let me know if that works for you :)
> 
> https://www.npmjs.com/package/sanity-plugin-media-library

Thank you very much. Will give this a try tomorrow.
