### ISSUE TITLE
UI Z-index issue on asset selection

### ISSUE THREAD

**Issue by khendrikse** [Aratramba/sanity-plugin-media-library#34]
I noticed that when using the media library as an asset selector, it shows parts of the underlying elements.

![image](https://user-images.githubusercontent.com/30577427/133625199-a8b18a9d-c218-4223-afd5-2f18935ccc35.png)

Just like mentioned in #28 

Using: 
    "@sanity/base": "^2.19.0",
    "@sanity/block-content-to-react": "^3.0.0",
    "@sanity/cli": "^2.19.1",
    "@sanity/components": "^2.14.0",
    "@sanity/core": "^2.19.2",
    "@sanity/dashboard": "^2.19.0",
    "@sanity/default-layout": "^2.19.0",
    "@sanity/default-login": "^2.19.0",
    "@sanity/desk-tool": "^2.19.3",
    "@sanity/image-url": "^1.0.1",
    "@sanity/studio-hints": "^2.19.0",
    "sanity-plugin-media-library": "^1.0.7"

It would be really wonderful if this could be solved :sparkles:

**Comment by Aratramba** [comment]
I've released a 2.0.0 version using Sanity UI instead of custom theming. The modal window is now smaller and fits over the document and not the panels. The z-index issue should be fixed.

https://www.npmjs.com/package/sanity-plugin-media-library

Could you check if this issue is resolved in 2.0.0?

**Comment by khendrikse** [comment]
@Aratramba yes this works! Wonderful.
