### ISSUE TITLE
Use Sanity UI components and inherit theme?

### ISSUE THREAD

**Issue by spacedawwwg** [Aratramba/sanity-plugin-media-library#9]
Great tool - Why this isn't a core feature of Sanity I don't know.

I was wondering, with the release of Sanity UI whether it might be worth looking at an enhancement to use that (inheriting custom themes along with it)?

https://www.sanity.io/ui

https://www.sanity.io/blog/streamline-your-studio-development-with-sanity-ui

**Comment by Aratramba** [comment]
Thanks @spacedawwwg :slightly_smiling_face:

I agree that using Sanity UI would make it look more in line with the rest of the product. The UI library is still kind of in beta though, so I think we'll hold off on implementing that for now. At least until it's more stable. We're definitely keeping an eye on it. 👀

**Comment by Aratramba** [comment]
I've released a 2.0.0 version using Sanity UI instead of custom theming. The interface is now white and theming is no longer an option. :)

https://www.npmjs.com/package/sanity-plugin-media-library
